# Copyright (c) 2026 LiteSDB contributors.
# SPDX-License-Identifier: LGPL-3.0-only
# This file is part of LiteSDB. See LICENSE for license details.
# Project: https://github.com/probair/litesdb

[package]
name = "litesdb-core"
description = "Embedded storage engine for LiteSDB"
edition.workspace = true
license.workspace = true
repository.workspace = true
rust-version.workspace = true
version.workspace = true

[lib]
name = "litesdb_core"

[features]
default = []
bench-metrics = []
archive = ["dep:sha2"]

[dependencies]
crc32fast = "1"
sha2 = { version = "0.10", optional = true }
